# On cree deux DockerFile : 
# Un pour les dev : Dockerfile.dev et un autre pour la production 
# 

FROM node:alpine

WORKDIR /app

COPY package.json ./

RUN npm install

COPY ./ ./

CMD ["npm", "run", "start"]